name: PlotMaster
authors: [Double0negative, MCSG]
version: 0.0.1
main: bukkit.org.mcsg.plotmaster.PlotMasterPlugin
depend: [GroovyRuntime]


commands:
    plot:
        description: Plot Master Command
        usage: /plot <command> <args>
        aliases: [pl, p, plots, pm, plotmaster]
